# Generated by Django 4.0.1 on 2022-01-18 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statusapp', '0004_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_by', models.CharField(blank=True, max_length=128, null=True)),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Not mentioned', 'Not mentioned')], default='Not mentioned', max_length=16, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_number', models.BigIntegerField(unique=True)),
                ('user_picture', models.FileField(blank=True, null=True, upload_to='Political/User/Profile/')),
                ('user_role', models.CharField(choices=[('Master Admin', 'Master Admin'), ('Employee', 'Employee'), ('Admin', 'Admin')], default='Employee', max_length=16)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=32, null=True)),
                ('community', models.CharField(blank=True, max_length=64, null=True)),
                ('caste', models.CharField(blank=True, max_length=64, null=True)),
                ('adhaar_card_no', models.CharField(blank=True, max_length=20, null=True)),
                ('adhaar_card_pic_front', models.FileField(blank=True, null=True, upload_to='Political/User/adhaar_cards/')),
                ('adhaar_card_pic_back', models.FileField(blank=True, null=True, upload_to='Political/User/adhaar_cards/')),
                ('pan_card_no', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_card_pic_front', models.FileField(blank=True, null=True, upload_to='Political/User/pan_cards/')),
                ('pan_card_pic_back', models.FileField(blank=True, null=True, upload_to='Political/User/pan_cards/')),
                ('voter_id_no', models.CharField(blank=True, max_length=20, null=True)),
                ('voter_id_pic_front', models.FileField(blank=True, null=True, upload_to='Political/User/voter_id/')),
                ('voter_id_pic_back', models.FileField(blank=True, null=True, upload_to='Political/User/voter_id/')),
                ('present_door_no', models.CharField(blank=True, max_length=32, null=True)),
                ('present_street', models.CharField(blank=True, max_length=64, null=True)),
                ('present_locality_name', models.CharField(blank=True, max_length=64, null=True)),
                ('present_landmark_name', models.CharField(blank=True, max_length=64, null=True)),
                ('present_city', models.CharField(blank=True, max_length=64, null=True)),
                ('present_state', models.CharField(blank=True, max_length=64, null=True)),
                ('present_pincode', models.CharField(blank=True, max_length=32, null=True)),
                ('present_country', models.CharField(blank=True, max_length=64, null=True)),
                ('alternate_mobile', models.BigIntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=64, null=True)),
                ('medical_issue', models.CharField(blank=True, max_length=512, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('registration_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Terminated', 'Terminated')], default='Pending', max_length=32)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried', max_length=32, null=True)),
                ('added_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statusapp.departments')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statusapp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_otp', models.CharField(max_length=10)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Login',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
                ('lastPasswordUpdated', models.DateTimeField(blank=True, null=True)),
                ('employee_uuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
