# Generated by Django 4.0.1 on 2022-01-10 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('primary_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='Department', max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('added_by', models.CharField(blank=True, max_length=128, null=True)),
                ('added_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
