# Generated by Django 4.0.1 on 2022-01-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
